# This GitHub action will check that the developer tools are run
# This checks code quality
# https://github.com/golangci/golangci-lint-action
# act --secret-file act.env --container-architecture linux/amd64 --workflows .github/workflows/analyze.yaml
name: analyze
on:
  push:
permissions:
  contents: read
jobs:
  lint:
    strategy:
      matrix:
        go: ['1.20']
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

# TODO
#  # test and benchmark
#  RUN go test -bench=. -benchmem ./...
#  # race condition
#  RUN CGO_ENABLED=1 GOOS=linux go build -v -a -race -installsuffix cgo -o . ./...
